db.createCollection("ThePersonSubjects")
db.ThePersonSubjects.insertMany([
    {PersonID: 1, MainSectorID:2},
    {PersonID: 1,MainSectorID: 1},
    {PersonID: 3,MainSectorID: 3},
    {PersonID: 3,MainSectorID: 4},
    {PersonID: 4,MainSectorID: 5},
    {PersonID: 4,MainSectorID: 6},
    {PersonID: 4,MainSectorID: 7},
    {PersonID: 5,MainSectorID: 3},
    {PersonID: 5,MainSectorID: 8},
    {PersonID: 6,MainSectorID: 1},
    {PersonID: 6,MainSectorID: 9},
    {PersonID: 7,MainSectorID: 1},
    {PersonID: 7,MainSectorID: 4},
    {PersonID: 8,MainSectorID: 1},
    {PersonID:8,MainSectorID: 4},
    {PersonID:9,MainSectorID: 8},
    {PersonID:9,MainSectorID: 4},
    {PersonID:10,MainSectorID: 1},
    {PersonID:10,MainSectorID: 4},
    {PersonID:11,MainSectorID: 1},
    {PersonID:11,MainSectorID: 4},
    {PersonID:12,MainSectorID: 8},
    {PersonID:12,MainSectorID: 4},
    {PersonID:13,MainSectorID: 4},
    {PersonID:14,MainSectorID: 1},
    {PererssonID:15,MainSectorID: 4},
    {PersonID:15,MainSectorID: 2},
    {PersonID:16,MainSectorID: 4},
    {PersonID:16,MainSectorID: 2},
    {PersonID:17,MainSectorID: 4},
    {PersonID:17,MainSectorID: 8},
    {PersonID:18,MainSectorID: 8},
    {PersonID:19,MainSectorID: 1},
    {PersonID:19,MainSectorID: 4},
    {PersonID:20,MainSectorID: 9},
    {PonID:20,MainSectorID: 8},
    {PersonID:20,MainSectorID: 10},
]

);